cesar:
  baseurl: ${CESAR_BASEURL:http://localhost:8080}
  crypto:
    salt: XXXXX-S ecretKey-XXXXX

spring:
  datasource:
    driver-class-name: ${CESAR_DATABASE_DRIVER:com.mysql.jdbc.Driver}
    url: jdbc:mysql://${CESAR_DATABASE_HOST:localhost}:${CESAR_DATABASE_PORT:3306}/${CESAR_DATABASE_SCHEMA:mixit}
    username: ${CESAR_DATABASE_USERNAME:mixit}
    password: ${CESAR_DATABASE_PASSWORD:mixit}
    max-wait: 10
  jpa :
    ddl-auto : validate
    hibernate.naming_strategy : org.hibernate.cfg.EJB3NamingStrategy
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    testOnBorrow : true
    validationQuery : SELECT 1
oauth:
  google:
    apiKey: XXXXX-SecretKey-XXXXX
    clientSecret: XXXXX-SecretKey-XXXXX
  twitter:
    apiKey: XXXXX-SecretKey-XXXXX
    clientSecret: XXXXX-SecretKey-XXXXX
---
spring:
  profiles: default
cesar:
  initializeDataWhenDbEmpty : true
---
spring:
  profiles: cloud
server:
  port: 80
