project:
  artifactId: cesar
  name: Cesar
  description: Mix-IT website

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
  git:
    branch: ${git.branch}
    id: ${git.commit.id}
  app:
    name: ${project.name}
    version: ${project.version}

cesar:
  baseurl: ${CESAR_BASEURL:http://localhost:8080}
  crypto:
    salt: ${CESAR_CRYPTO_SALT:XXXXX-S ecretKey-XXXXX}
  mail:
    smtp:
      host: ${CESAR_MAIL_HOST:smtp.gmail.com}
      user: ${CESAR_MAIL_USER:contact@mix-it.fr}
      password: ${CESAR_MAIL_PASSWORD:XXXXX-SecretKey-XXXXX}
      auth: true
      port: ${CESAR_MAIL_PORT:587}
      starttls: true
    from: Mix-IT <contact@mix-it.fr>

oauth:
  google:
    apiKey: ${OAUTH_GOOGLE_APIKEY:XXXXX-SecretKey-XXXXX}
    clientSecret: ${OAUTH_GOOGLE_SECRET:XXXXX-SecretKey-XXXXX}
  twitter:
    apiKey: ${OAUTH_TWITTER_APIKEY:XXXXX-SecretKey-XXXXX}
    clientSecret: ${OAUTH_TWITTER_SECRET:XXXXX-SecretKey-XXXXX}

spring:
  datasource:
    driver-class-name: ${CESAR_DATABASE_DRIVER:com.mysql.jdbc.Driver}
    url: jdbc:mysql://${CESAR_DATABASE_HOST:localhost}:${CESAR_DATABASE_PORT:3306}/${CESAR_DATABASE_SCHEMA:mixit}
    username: ${CESAR_DATABASE_USERNAME:mixit}
    password: ${CESAR_DATABASE_PASSWORD:mixit}
    max-wait: 10
  jpa :
    ddl-auto : validate
    hibernate.naming_strategy : org.hibernate.cfg.EJB3NamingStrategy
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    testOnBorrow : true
    validationQuery : SELECT 1
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

management:
  context-path: /monitoring

server:
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048
---
spring:
  profiles: default
cesar:
  initializeDataWhenDbEmpty : true
---
spring:
  profiles: cloud
  datasource:
    min-idle: 1
    max-idle: 5
    max-active: 10
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
server:
  port: 80
